/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRoundsRouteImport } from './routes/_dashboard.rounds'
import { Route as DashboardProxiesRouteImport } from './routes/_dashboard.proxies'
import { Route as DashboardMetricsRouteImport } from './routes/_dashboard.metrics'
import { Route as DashboardLogsRouteImport } from './routes/_dashboard.logs'
import { Route as DashboardConfigRouteImport } from './routes/_dashboard.config'
import { Route as DashboardAgeRouteImport } from './routes/_dashboard.age'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoundsRoute = DashboardRoundsRouteImport.update({
  id: '/rounds',
  path: '/rounds',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProxiesRoute = DashboardProxiesRouteImport.update({
  id: '/proxies',
  path: '/proxies',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMetricsRoute = DashboardMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfigRoute = DashboardConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgeRoute = DashboardAgeRouteImport.update({
  id: '/age',
  path: '/age',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/age': typeof DashboardAgeRoute
  '/config': typeof DashboardConfigRoute
  '/logs': typeof DashboardLogsRoute
  '/metrics': typeof DashboardMetricsRoute
  '/proxies': typeof DashboardProxiesRoute
  '/rounds': typeof DashboardRoundsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/age': typeof DashboardAgeRoute
  '/config': typeof DashboardConfigRoute
  '/logs': typeof DashboardLogsRoute
  '/metrics': typeof DashboardMetricsRoute
  '/proxies': typeof DashboardProxiesRoute
  '/rounds': typeof DashboardRoundsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/age': typeof DashboardAgeRoute
  '/_dashboard/config': typeof DashboardConfigRoute
  '/_dashboard/logs': typeof DashboardLogsRoute
  '/_dashboard/metrics': typeof DashboardMetricsRoute
  '/_dashboard/proxies': typeof DashboardProxiesRoute
  '/_dashboard/rounds': typeof DashboardRoundsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/age' | '/config' | '/logs' | '/metrics' | '/proxies' | '/rounds'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/age' | '/config' | '/logs' | '/metrics' | '/proxies' | '/rounds'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_dashboard/age'
    | '/_dashboard/config'
    | '/_dashboard/logs'
    | '/_dashboard/metrics'
    | '/_dashboard/proxies'
    | '/_dashboard/rounds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/rounds': {
      id: '/_dashboard/rounds'
      path: '/rounds'
      fullPath: '/rounds'
      preLoaderRoute: typeof DashboardRoundsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/proxies': {
      id: '/_dashboard/proxies'
      path: '/proxies'
      fullPath: '/proxies'
      preLoaderRoute: typeof DashboardProxiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/metrics': {
      id: '/_dashboard/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof DashboardMetricsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/logs': {
      id: '/_dashboard/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/config': {
      id: '/_dashboard/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof DashboardConfigRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/age': {
      id: '/_dashboard/age'
      path: '/age'
      fullPath: '/age'
      preLoaderRoute: typeof DashboardAgeRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAgeRoute: typeof DashboardAgeRoute
  DashboardConfigRoute: typeof DashboardConfigRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardMetricsRoute: typeof DashboardMetricsRoute
  DashboardProxiesRoute: typeof DashboardProxiesRoute
  DashboardRoundsRoute: typeof DashboardRoundsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgeRoute: DashboardAgeRoute,
  DashboardConfigRoute: DashboardConfigRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardMetricsRoute: DashboardMetricsRoute,
  DashboardProxiesRoute: DashboardProxiesRoute,
  DashboardRoundsRoute: DashboardRoundsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
